### ISSUE TITLE
module 'tensorflow' has no attribute 'Optimizer'

### ISSUE THREAD

**Issue by jianminli55** [ProHiryu/albert-chinese-ner#1]
已经把tensorflow版本更改为1.15.0,但是还是出现这个问题呢

**Comment by jianminli55** [comment]
应该要把tf.Optimizer改成tf.train.Optimizer

**Comment by ProHiryu** [comment]
有具体细节吗？

**Comment by jianminli55** [comment]
> 有具体细节吗？

忘记是optimization_finetuning.py还是optimization.py，里面有个地方写着tf.Optimizer,所以运行的时候出现报错

**Comment by ProHiryu** [comment]
改过来了之后运行正常吗？改为tf.train.Optimizer

**Comment by jianminli55** [comment]
> 改过来了之后运行正常吗？改为tf.train.Optimizer

是的，改过来之后就可以正常运行了
