### ISSUE TITLE
跑代码的时候遇到了一个问题想请教

### ISSUE THREAD

**Issue by 652994331** [ProHiryu/albert-chinese-ner#12]
想问下，跑的时候出现了训练刚开始就结束，显示train_loop marked as finished 的问题，提示说可能是input 是空， 不过感觉不是那个问题好像， 数据应该是正常的。谢谢

**Comment by ProHiryu** [comment]
是不是训练配置问题

**Comment by foreverxujiahuan** [comment]
程序killed怎么办

**Comment by wangyi888** [comment]
> 想问下，跑的时候出现了训练刚开始就结束，显示train_loop marked as finished 的问题，提示说可能是input 是空， 不过感觉不是那个问题好像， 数据应该是正常的。谢谢

应该是你设置的训练轮数小于checkpoint已有的轮数，把checkpoint干掉再训练试试，或者把轮数调大点
