### ISSUE TITLE
predict_prob

### ISSUE THREAD

**Issue by ssz1984** [ProHiryu/albert-chinese-ner#14]
想要获取输出标签前那个用于判定的分数矩阵，类似predict_prob，是在代码哪层呢？
另外想要用sklearn里的东西，怎么将这个Albert做出个接口呢？
Many thanks in advance!!

**Comment by shengzing** [comment]
您好，请问如果使用serving部署该如何设置呢？多谢

**Comment by ProHiryu** [comment]
> 您好，请问如果使用serving部署该如何设置呢？多谢

保存为serving的pd文件 定义好输入输出的签名，然后加载就可以了

**Comment by ProHiryu** [comment]
> 想要获取输出标签前那个用于判定的分数矩阵，类似predict_prob，是在代码哪层呢？
> 另外想要用sklearn里的东西，怎么将这个Albert做出个接口呢？
> Many thanks in advance!!

就是logits 取出来就行了
