### ISSUE TITLE
结果（精确度）领先bert 吗　存在疑问

### ISSUE THREAD

**Issue by 652994331** [ProHiryu/albert-chinese-ner#15]
我用albert_large_zh 做了详细的对比试验　和 bert 。在NER任务上的表现是不如bert base的，　分开来看　loc per 可以做到93%左右　org 最高做到89%左右　bert 在更少的训练步数下　loc per 做到95%及以上，　org 可以做到91%. 这其中　两个模型都对照使用了　1.基础模型 2.基础模型＋crf 3.基础模型+bilstm+crf
结果都是做不过. 您这个结果中　我只看到了eval_accuracy，　请问您有没有具体看过没一种标签的准确率呢？可以放出来看看吗　谢谢

**Comment by ProHiryu** [comment]
没有仔细看，您可以统计一下，二者本来已经触及了深度学习的边界，太纠结小数字也没有必要
