### ISSUE TITLE
albert_ner.py 脚本BUG

### ISSUE THREAD

**Issue by wangle1218** [ProHiryu/albert-chinese-ner#17]
584行
d = tf.data.Dataset.from_tensor_slices({
        "input_ids":
            tf.constant(
                all_input_ids, shape=[num_examples, seq_length],
                dtype=tf.int32),
        "input_mask":
            tf.constant(
                all_input_mask,
                shape=[num_examples, seq_length],
                dtype=tf.int32),
        "segment_ids":
            tf.constant(
                all_segment_ids,
                shape=[num_examples, seq_length],
                dtype=tf.int32),
        "label_ids":
            tf.constant(all_label_ids, shape=[num_examples], dtype=tf.int32),
    })
shape=[num_examples, seq_length]，shape=[num_examples] 应该有问题，这里总是跑不通

**Comment by ProHiryu** [comment]
具体报的什么错呢？
