### ISSUE TITLE
how many epochs for finetuning on NER dataset?

### ISSUE THREAD

**Issue by dqqcasia** [ProHiryu/albert-chinese-ner#2]
Hello, I am doing experiments on the MSRA NER dataset using albert. But after 3 epochs, the f1 score can only reach 82 or so. I use the conlleval.py script to calculate the metrics. How many epochs do you usually run for finetuning on NER dataset? Looking forward to your reply.

**Comment by ProHiryu** [comment]
Just 3 epochs

**Comment by dqqcasia** [comment]
Thanks! I got it!

**Comment by dqqcasia** [comment]
One more question, how does the difference between f1 scores on NER task of albert-tiny, albert-base and albert-large models?

**Comment by ProHiryu** [comment]
I only considered one situation on albert-base, but i think albert-large will performance better theoretically.
