### ISSUE TITLE
number of label_test.txt and token_test.txt are dismatch

### ISSUE THREAD

**Issue by martin3252** [ProHiryu/albert-chinese-ner#3]
Hi,我改了一些label,讓程式變成sequence labeling的task，但是經過訓練及測試，發現預測的label檔案和token_test檔案長度不同(有缺字的情況)，不知道是什麼原因，所以來詢問版大，謝謝。
![螢幕快照 2019-10-22 下午4 22 42](https://user-images.githubusercontent.com/29199392/67268958-53618200-f4e8-11e9-88ae-b8197a2fc1c4.png)
![螢幕快照 2019-10-22 下午4 22 54](https://user-images.githubusercontent.com/29199392/67268971-58263600-f4e8-11e9-84a5-f8e720b78cfd.png)
另外我有檢查過不是max_seq_length的問題

**Comment by ProHiryu** [comment]
是不是因为标点符号的处理问题呢？因为我看你的case像是？这个符号没有识别出来

**Comment by martin3252** [comment]
經過檢查發現是因為predict label 變為 0, 因此不會被寫入檔案，所以程式看來是沒問題的。
