### ISSUE TITLE
loss值无法下降

### ISSUE THREAD

**Issue by songsa1** [ProHiryu/albert-chinese-ner#32]
您好，我发现您的这套代码，无法让loss值下降啊，即使使用您提供的数据集，loss值也保持在十几二十几的

**Comment by ProHiryu** [comment]
LOSS不重要，关注准确率，也没有优化吗？

**Comment by songsa1** [comment]
准确率确实还可以，但是loss过大在测试集上效果应该会比较差的哦

**Comment by ProHiryu** [comment]
试着加大数据量吧，或者尝试一些优化方法
