### ISSUE TITLE
data数据问题

### ISSUE THREAD

**Issue by Rebecca7901** [ProHiryu/albert-chinese-ner#39]
请问data的数据怎么做

**Comment by ProHiryu** [comment]
哪种类型的data？

**Comment by Rebecca7901** [comment]
bio数据怎么来的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ProHiryu/albert-chinese-ner"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月7日(星期二) 上午10:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ProHiryu/albert-chinese-ner] data数据问题 (#39)





 
哪种类型的data？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ProHiryu** [comment]
训练和测试的数据自己标注，我应该有自带的数据
