### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension size must be evenly divisible by 1408 but is 122880 for 'loss/Reshape_1' (op: 'Reshape') with input shapes: [8192,15], [3] and with input tensors computed as partial shapes: input[1] = [?,128,11].

### ISSUE THREAD

**Issue by wzjj98** [ProHiryu/albert-chinese-ner#4]
ValueError: Dimension size must be evenly divisible by 1408 but is 122880 for 'loss/Reshape_1' (op: 'Reshape') with input shapes: [8192,15], [3] and with input tensors computed as partial shapes: input[1] = [?,128,11].

**Comment by jianminli55** [comment]
是tag个数对不上导致的，你在albert_ner里把有11的地方都改成15，同时metric_fn也修改一下就好了
