### ISSUE TITLE
如果要换成albert_tiny的话，请问需要在哪里修改呢？

### ISSUE THREAD

**Issue by jianminli55** [ProHiryu/albert-chinese-ner#5]
当把模型换成albert_tiny版本的时候，出现报错了：ValueError: Shape of variable bert/embeddings/LayerNorm/beta:0 ((312,)) doesn't match with shape of tensor bert/embeddings/LayerNorm/beta ([768]) from checkpoint reader.

**Comment by ProHiryu** [comment]
修改--bert_config_file为tiny，文件在config目录下

**Comment by jianminli55** [comment]
> 修改--bert_config_file为tiny，文件在config目录下
嗯，我就是这么修改的，但是就出现了：ValueError: Shape of variable bert/embeddings/LayerNorm/beta:0 ((312,)) doesn't match with shape of tensor bert/embeddings/LayerNorm/beta ([768]) from checkpoint reader.的报错

**Comment by ProHiryu** [comment]
刚刚update了一下，你现在指定一下albert_config_tiny.json这个文件就行了

**Comment by jianminli55** [comment]
> 刚刚update了一下，你现在指定一下albert_config_tiny.json这个文件就行了

哇，非常感谢
