### ISSUE TITLE
module 'tensorflow' has no attribute 'Optimizer'

### ISSUE THREAD

**Issue by YueCongPKU** [ProHiryu/albert-chinese-ner#7]
tf.Optimizer 是TF2.0才有的吧，  optimization_finetuning.py 第87行 class AdamWeightDecayOptimizer(tf.Optimizer) 是怎么回事？ 报module 'tensorflow' has no attribute 'Optimizer'

**Comment by Delysky** [comment]
你用tf.train.Optimizer试下，

**Comment by ProHiryu** [comment]
已修复

**Comment by oniondai** [comment]
> 已修复

请问如何修复的呢？
